default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  port: 5432
  username: postgres
  password: postgres
  pool: 5

development:
  <<: *default
  database: frontend_bootstrap_development

test:
  <<: *default
  database: frontend_bootstrap_test

production:
  <<: *default
  database: frontend_bootstrap_production
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  host: <%= ENV['PROD_DB_SERVER'] %>
