default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  port: 5432
  username: postgres
  password: postgres
  pool: 5

development:
  <<: *default
  database: juketape_development

test:
  <<: *default
  database: juketape_test

staging:
  <<: *default
  database: juketape_staging
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  host: <%= ENV['PROD_DB_SERVER'] %>

production:
  <<: *default
  database: juketape_production
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  host: <%= ENV['PROD_DB_SERVER'] %>
