# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 90a8ccff9c41f8991c554da32ba9567f8797bd705b937da7ee5dfe12f4d914934b91f662825ac7d0bb7e1915767ca85e8a06c39bc8367883b7e1d77e71c6dd09
  fb_api_key: 300418953631254
  fb_secret: 86afb840360b72798e708fc04f41de05
  fb_app_id: 300418953631254

test:
  secret_key_base: b177df27f40cd216c0e9efd9dbe8292834ab8c0117716c085d2496457df9a38a9d774db202f2340d73490b9be9945afbd1389fabf26d067d58d61462364e6bf9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  fb_api_key: 300418953631254
  fb_secret: 86afb840360b72798e708fc04f41de05
  fb_app_id: 300418953631254
